"""DMCA notice text generation (IMPLEMENTATION.md §3.6).

Text-only Gemini call: creator profile + platform-specific required fields
+ asset description + incident evidence -> plain-text notice body. Falls
back to canned boilerplate on any failure (§3.7) so the demo never breaks.
"""
from __future__ import annotations

from ..models import Asset, CreatorProfile, Incident
from .gemini_client import TEXT_MODEL, get_client
from .platform_templates import PLATFORM_TEMPLATES


def _asset_description(asset: Asset) -> str:
    if asset.fingerprint is None:
        return "A creative asset uploaded by the creator."
    fp = asset.fingerprint
    features = "; ".join(fp.distinguishing_features) if fp.distinguishing_features else "n/a"
    colors = ", ".join(fp.dominant_colors) if fp.dominant_colors else "n/a"
    return f"Subject: {fp.subject}. Dominant colors: {colors}. Distinguishing features: {features}."


def _build_prompt(profile: CreatorProfile, platform: str, asset: Asset, incident: Incident) -> str:
    template = PLATFORM_TEMPLATES.get(platform, {})
    required_fields = template.get("required_fields", [])
    submission_method = template.get("submission_method", "Web form")

    return f"""You are a legal-assistance drafting tool. Draft a formal DMCA takedown
notice to be submitted to {platform} (submission method: {submission_method}).

RIGHTS HOLDER (copyright owner filing the complaint):
Name: {profile.name}
Email: {profile.email}
Address: {profile.address}
Phone: {profile.phone}

PLATFORM: {platform}
This platform's takedown form/process requires the following fields to be
addressed in the notice body (invent plausible placeholder values clearly
marked as such if the exact value is unknown, e.g. "[insert video URL]"):
{", ".join(required_fields) if required_fields else "n/a"}

ORIGINAL PROTECTED ASSET DESCRIPTION:
{_asset_description(asset)}

EVIDENCE OF INFRINGEMENT (from automated visual comparison):
- Similarity score: {incident.similarity_score}/100
- Reasoning: {incident.reasoning}
- Leaked/infringing content found at: {incident.leak_url}

Write a complete, professional DMCA takedown notice as plain text
(no markdown, no code fences). Include: a statement of ownership, a
description of the copyrighted work, the location of the infringing
material, a statement of good faith belief, a statement of accuracy
under penalty of perjury, and the rights holder's contact info and
signature line. Keep it concise (under 300 words).
"""


def _fallback_notice(profile: CreatorProfile, platform: str, asset: Asset, incident: Incident) -> str:
    template = PLATFORM_TEMPLATES.get(platform, {})
    submission_method = template.get("submission_method", "Web form")
    return f"""DMCA TAKEDOWN NOTICE

To: {platform} Copyright Agent (via {submission_method})
From: {profile.name}
Email: {profile.email}
Address: {profile.address}
Phone: {profile.phone}

I am the copyright owner of the original work described below, and I have
a good faith belief that the material identified is being used without my
authorization on {platform}.

Description of copyrighted work: {_asset_description(asset)}

Location of infringing material: {incident.leak_url}

Our automated visual-similarity system flagged this content with a
similarity score of {incident.similarity_score}/100. Reasoning: {incident.reasoning}

I have a good faith belief that use of the copyrighted material described
above is not authorized by the copyright owner, its agent, or the law.

I swear, under penalty of perjury, that the information in this
notification is accurate and that I am the copyright owner, or am
authorized to act on behalf of the owner, of an exclusive right that is
allegedly infringed.

Signature: {profile.name}
Date: (auto-generated by GhostTrace)
"""


def generate_dmca_notice(profile: CreatorProfile, platform: str, asset: Asset, incident: Incident) -> str:
    try:
        client = get_client()
        prompt = _build_prompt(profile, platform, asset, incident)
        resp = client.models.generate_content(
            model=TEXT_MODEL,
            contents=[prompt],
        )
        text = (resp.text or "").strip()
        if not text:
            raise ValueError("empty response text from Gemini")
        print(f"[dmca] generate_dmca_notice LIVE ok for platform={platform!r} incident={incident.id!r}")
        return text
    except Exception as exc:  # noqa: BLE001
        print(
            f"[dmca] generate_dmca_notice FALLBACK (reason: {exc!r}) "
            f"for platform={platform!r} incident={incident.id!r}"
        )
        return _fallback_notice(profile, platform, asset, incident)
